Домашка по Jetty и Jersey
k-vasiliev/hh-java-servers-homework pull request #3
Opened 2021-02-19 16:51 UTC by JeyXeon

Я поздновато понял, что можно использовать класс Response для того, чтобы корявенько строки не возвращать, но ручками потестил вроде работает) И там пара проблем была во втором приложении, NoClassDefFoundException получал, исправилось добавлением двух зависимостей, как я понял какой-то конфликт версий был.

2021-02-20 09:25 UTC, Azadios requested changes
Привет. Кирилл, кажется, занят. Пока ждём его ревью, я решил посмотреть твой пр. Нашёл несколько проблем, подумал, что тебе будет интересно узнать. Ну и я там оставил несколько вопросов, они не риторические, мне правда интересно :)

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/servlets/CounterOperationsServlet.java
> +        int n = Integer.parseInt(request.getParameter("subtraction"));
У тебя тут может быть exception при парсинге, если в качестве параметра не передано число, что, думаю, лучше обработать в сервлете (например, вернуть BAD_REQUEST код), чем уронить его c server error. + по заданию нас просили получить это значение из хедера с именем «Subtraction-Value» (это можно сделать просто поменяв вызов getParameter на getHeader)

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/servlets/CounterClearServlet.java
> +        if (cookieCheck(request.getCookies())) {
getCookies может вернуть null, если куков нет вовсе. Тогда это может привести совсем к печальному, сервер вернёт стектрейс пользователю. Вот что у меня получилось
<details>
  <summary>Опасный результат запроса</summary>
  
curl -i -X POST http://localhost:8081/counter/clear
HTTP/1.1 500 Server Error
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 2143
Connection: close
Server: Jetty(9.4.0.RC1)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /counter/clear. Reason:
<pre>    Server Error</pre></p><h3>Caused by:</h3><pre>java.lang.NullPointerException: Cannot read the array length because &quot;cookies&quot; is null
        at servlets.CounterClearServlet.cookieCheck(CounterClearServlet.java:33)
        at servlets.CounterClearServlet.doPost(CounterClearServlet.java:19)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:838)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:552)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1584)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1221)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:487)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1134)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:560)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:318)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:265)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:97)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
        at java.base/java.lang.Thread.run(Thread.java:832)
</pre>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.0.RC1</a><hr/>

</body>
</html>
  
</details>
В этом стектрейсе могут быть детали, которыми могут воспользоваться злоумышленники.

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/servlets/CounterClearServlet.java
> +                return c.getValue().length() >= 10;
Вроде должно быть просто >10 :)

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/servlets/CounterClearServlet.java
> +            if (c.getName().equalsIgnoreCase("hh-auth")) {
Почему игноркейс?

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/service/CounterService.java
> +    private int count;
Будь осторожен с обычным интом. В многопоточности может возникнуть состояние гонки. [Вот здесь](https://github.com/k-vasiliev/hh-java-servers-homework/pull/1#discussion_r576058373) Кирилл писал про это.

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +    public static ServletContainer getInstance() {
А зачем синглтон?

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +    public String incrementByOne(@CookieParam("hh-auth") String cookie) {
А здесь ты уже учёл проблемы, которые есть в голых сервлетах :) Только, кажется, на инкремент не нужна была проверка, только на обнуление

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +    public String reset() {
Вот здесь нужна авторизация при помощи куки

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +        OffsetDateTime now = OffsetDateTime.now();
Есть LocalDateTime, который сразу в ISO работает. Код получится попроще

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +    public void setCount(int count) {
Чем оправдана возможность изменения значений count вне сервлета?

2021-02-20 09:25 UTC, Azadios commented on jersey/pom.xml
> +            <version>9.4.0.RC1</version>
Нам в properties оставили переменную jettyVersion. Думаю, это был намёк на необходимую версию. Использовать эту переменную можно так ${jettyVersion}. Но, пожалуй, главная причина использовать переменную - она используется в нескольких зависимостях. Вероятно, эти версии должны быть одинаковыми, чтобы стабильно работать вместе. Тогда при переходе на новую версию, достаточно будет изменить одну переменную

2021-02-20 09:25 UTC, Azadios commented on jersey/src/main/java/service/ServletContainer.java
> +    public String decrementByN(@QueryParam("subtraction") int n) {
Здесь возникнет подобная голым сервлетам проблема, только она будет чутка иная. С ошибкой при парсинге ты не вылетишь, но, в случае, если тебе не передадут в запросе этот параметр, то у тебя этот int будет проинициализирован 0, хотя, возможно, стоило бы вернуть BAD_REQUEST. Это легко решается заменой на Integer, который ссылочный тип, а значит может быть null. Так ты сможешь различить переданный 0 от отсутствующего параметра.

Ну и опять же @HeaderParam("Subtraction-Value")

2021-02-20 09:25 UTC, Azadios commented on servlet/src/main/java/service/CounterService.java
> +    public static CounterService getInstance() {
Опять же чем оправдан синглтон?

2021-02-21 18:35 UTC, k-vasiliev commented on servlet/pom.xml
> +            <version>2.15</version>
Стоит вынести в переменную. Это не только для красоты - проблема в том, что у подобных либ версии совпадают не просто так и если у тебя одна из них будет 2.15, то возможно либы будут несовместимы и приложение не поедет

2021-02-21 18:35 UTC, k-vasiliev commented on servlet/src/main/java/service/CounterService.java
> +            instance.setCount(0);
Лучше в конструкторе сразу это сделать

2021-02-21 18:35 UTC, k-vasiliev commented on servlet/src/main/java/service/CounterService.java
> +    public static CounterService getInstance() {
В случае сервиса - почему бы и нет? Если можно обойтись одним инстансом на все приложение, то стоит так и сделать, только убедиться, что твой инстанс тред-сейф :) По факту у тебя похожее решение, но только с использованием контекста, а тут без него

2021-02-21 18:35 UTC, k-vasiliev commented on jersey/src/main/java/service/ServletContainer.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ISO_DATE_TIME;
👍

2021-02-21 18:35 UTC, k-vasiliev commented on jersey/src/main/java/AppConfig.java
> +        s.add(ServletContainer.getInstance());
Идея понятна, но твой синглтон должен быть thread-safe для того, чтобы хранить внутри состояние. Я бы рекомендовал не заморачиваться с тред-сейф сервлетами, а сделать тредсейф хранилище для счетчика и из сервлета его дергать. Это может быть хоть статические методы какого-то класса

2021-02-21 18:56 UTC, k-vasiliev commented on servlet/src/main/java/servlets/CounterOperationsServlet.java
> +        response.getWriter().println("Current value of counter is " + count);
Просто значение нужно вернуть

2021-02-21 18:57 UTC, k-vasiliev commented
По jersey-приложению:
Когда вызываю `/counter/clear` без куки, то получаю 404, хотелось бы получить другую ошибку
Когда вызываю декремент без хедера, то получаю 200, хотелось бы получить другую ошибку 

Что-то работает не так. Попробуй сам протестировать такой кейс:
Сделать 3 инкремента и потом один декремент на "2". Я в тесте получил значение "3"

2021-02-23 19:45 UTC, k-vasiliev commented on jersey/src/main/java/ServletContainer.java
> +        return "Cookie is required";
Ты вернешь тут код 200, который клиент воспримет как "все ок", а у тебя по факту ошибка. Лучше вернуть 4**

2021-02-24 11:25 UTC, k-vasiliev approved these changes

2021-02-24 11:25 UTC, closed without merging